# theme.toml for the Vex Hugo theme

name = "Medifast"
license = "MIT"
licenselink = "https://github.com/ronibd0/medifast.store/master/LICENSE"
description = "medifast by goc ported to Hugo"
homepage = "https://github.com/ronibd0/medifast.store"
tags = ["medifast", "medifas store", "healthy-living", "nutri", "pure-protein", "protein-shake","medifast-products", "medifast-bar", "medifast-cooking", "medifast-optavia", "medifast-coach", "optavia"]
features = ["onepage", "product"]
min_version = "0.62.2"

[author]
  name = "Medifast"
  homepage = "https://medifast.store/"

[original]
  name = "gox"
  homepage = "https://github.com/ronibd0/medifast.store/master"
